### ISSUE TITLE
App still in-dev?

### ISSUE THREAD

**Issue by Laicure** [whataudoinghere/CPL#9]
Hi @whataudoinghere,

Is the app still active?
I liked it so much that I am even willing to go prem/donate but last commit/release was like 2 years ago?
You still alive?

(app in Google Play was updated last Jan 27, 2020 @ version 1.14.10.1, is there another repo for this?)

**Comment by whataudoinghere** [comment]
Hi, Laicure
The app (and I) are still alive. I closed the sourse code of CPL, because i don't want paid clones of CPL in the Google Play and they have already appeared (see https://play.google.com/store/apps/details?id=me.craftsapp.pielauncher for example).
The situation when other developers are deceiving people and at the same time making money on my work, I absolutely do not like. Therefore so.

**Comment by Laicure** [comment]
> Hi, Laicure
> The app (and I) are still alive. I closed the sourse code of CPL, because i don't want paid clones of CPL in the Google Play and they have already appeared (see https://play.google.com/store/apps/details?id=me.craftsapp.pielauncher for example).
> The situation when other developers are deceiving people and at the same time making money on my work, I absolutely do not like. Therefore so.

Good to know! :D ;) (can you mention that you closed source it? at least in the readme?)
oh wtf! Those paid clones are sh*t!
No worries, I still love your work.
It runs smooth and no battery drain.
Also, the permissions are just right!
I'll donate by sometime, just need to get my next paycheck hehe! ;)
